new ip & add port 18080

diff --git a/.github/workflows/docker-deploy.yml b/.github/workflows/docker-deploy.yml
--- a/.github/workflows/docker-deploy.yml
+++ b/.github/workflows/docker-deploy.yml
@@ -41,7 +41,13 @@ jobs:
       - name: Parse inventory file to get IP address
         id: parse_inventory
         run: |
-          SERVER_HOST=$(awk -F'=' '/ansible_host/ {split($2, arr, " "); print arr[1]}' log-app/inventory.ini | head -n 1)
+          # Извлечение IP-адреса из группы [web]
+          SERVER_HOST=$(awk -F'=' '/\[web\]/,/^$/{if ($0 ~ /ansible_host/) {split($2, arr, " "); print arr[1]; exit}}' ../../ansible/inventory.ini)
+          if [ -z "$SERVER_HOST" ]; then
+            echo "Error: Unable to extract SERVER_HOST from inventory.ini"
+            exit 1
+          fi
+          echo "Extracted SERVER_HOST: $SERVER_HOST"
           echo "SERVER_HOST=$SERVER_HOST" >> $GITHUB_ENV
 
       # 6. Копирование Docker-образа на сервер
